name: .NET-Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Loggin to AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: AWS CLI Update
        run: dotnet tool update -g Amazon.Lambda.Tools

      - name: Restore
        run: dotnet restore TechChallenge.Api.sln

      - name: Build
        run: dotnet build --no-restore TechChallenge.Api.sln

      - name: Deploy AWS Lambda
        id: create_package
        working-directory: ./src/TechChallenge.Api
        run: dotnet lambda deploy-serverless -sn TechChallengeLambdaAuth -sb techchallenge-terraform-s3-auth